/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "hello.h"

char **hello_1_svc(char **msg, struct svc_req *rqstp){

	if(msg == NULL)
		printf("%s\n", "ASD");
	else
		printf("%s\n", *msg);

	return msg;
}
