/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "hello.h"

bool_t
xdr_str_t (XDR *xdrs, str_t *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, 255))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_input_string_data (XDR *xdrs, input_string_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->input_data, 255))
		 return FALSE;
	return TRUE;
}
