/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HELLO_H_RPCGEN
#define _HELLO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *str_t;

struct input_string_data {
	char *input_data;
};
typedef struct input_string_data input_string_data;


#define HELLOPROG 12345
#define HELLOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HELLO 1
extern  char ** hello_1(char **, CLIENT *);
extern  char ** hello_1_svc(char **, struct svc_req *);
extern int helloprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HELLO 1
extern  char ** hello_1();
extern  char ** hello_1_svc();
extern int helloprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str_t (XDR *, str_t*);
extern  bool_t xdr_input_string_data (XDR *, input_string_data*);
extern  bool_t xdr_input_string_data (XDR *, input_string_data*);

#else /* K&R C */
extern bool_t xdr_str_t ();
extern bool_t xdr_input_string_data ();
extern bool_t xdr_input_string_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HELLO_H_RPCGEN */
